services:
  - type: web
    name: somax
    env: java
    plan: free
    buildCommand: cd backend && ./mvnw clean package
    startCommand: cd backend && java -jar target/somax-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 25
      - key: APP_FRONTEND_BASE_URL
        value: CHANGE_ME
      - key: APP_JWT_SECRET
        value: CHANGE_ME
      - key: APP_STACKAI_API_KEY
        value: CHANGE_ME
      - key: APP_STACKAI_WORKFLOW_ID
        value: CHANGE_ME
      - key: APP_SENDGRID_API_KEY
        value: CHANGE_ME
      - key: APP_SENDGRID_FROM_EMAIL
        value: no-reply@somax.local
      - key: APP_SENDGRID_FROM_NAME
        value: Somax
      - key: APP_CLOUDINARY_CLOUD_NAME
        value: CHANGE_ME
      - key: APP_CLOUDINARY_API_KEY
        value: CHANGE_ME
      - key: APP_CLOUDINARY_API_SECRET
        value: CHANGE_ME
      - key: SPRING_H2_CONSOLE_ENABLED
        value: "false"
